### ISSUE TITLE
Error when executing command "/?"

### ISSUE THREAD

**Issue by sgdc3** [LapisBlue/Pore#13]
```
[WARN] [Sponge] A handler raised an error when handling an event
org.bukkit.command.CommandException: Unhandled exception executing '?' in org.bukkit.command.defaults.HelpCommand(help)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:1.0.0-SNAPSHOT]
13:19:15 at blue.lapis.pore.impl.PoreServer.dispatchCommand(PoreServer.java:485) ~[PoreServer.class:1.0.0-SNAPSHOT]
at blue.lapis.pore.Pore.onCommand(Pore.java:132) ~[Pore.class:1.0.0-SNAPSHOT]
at org.spongepowered.mod.event.handler.CommandEventHandler_Pore_onCommand3.handle(Unknown Source) ~[?:?]
at org.spongepowered.mod.event.SpongeEventBus.callListener(SpongeEventBus.java:234) [SpongeEventBus.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
at org.spongepowered.mod.event.SpongeEventBus.post(SpongeEventBus.java:280) [SpongeEventBus.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:224) [SimpleCommandService.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:85) [cl.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400) [po.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:365) [po.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: org.apache.commons.lang.NotImplementedException: Code is not implemented
at blue.lapis.pore.impl.PoreServer.getHelpMap(PoreServer.java:646) ~[PoreServer.class:1.0.0-SNAPSHOT]
at org.bukkit.command.defaults.HelpCommand.execute(HelpCommand.java:71) ~[HelpCommand.class:1.0.0-SNAPSHOT]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:1.0.0-SNAPSHOT]
... 12 more
```

**Comment by sgdc3** [comment]
If the code isn't already implemented at least print a message instead of a error...

**Comment by Minecrell** [comment]
Pore is not supposed to be used in production yet, it's quite hard to keep up with all the API changes in the last time. Once we got more implemented this will be fixed

**Comment by simon816** [comment]
It _does_ print an error
```
Caused by: org.apache.commons.lang.NotImplementedException: Code is not implemented
````
