### ISSUE TITLE
Scheduler is throwing an exception when unregistering tasks by plugin

### ISSUE THREAD

**Issue by sgdc3** [LapisBlue/Pore#14]
```
13:42:35 [INFO] [com.earth2me.essentials.Essentials] [Essentials] Disabling Essentials vTeamCity
13:42:35 [ERROR] [pore] Error occurred (in the plugin loader) while cancelling tasks for Essentials vTeamCity (Is it up to date?)
13:42:35 java.lang.ClassCastException: org.spongepowered.common.service.scheduler.ScheduledTask cannot be cast to org.spongepowered.api.plugin.PluginContainer
13:42:35 at org.spongepowered.common.service.scheduler.SchedulerHelper.getScheduledTasks(SchedulerHelper.java:156) ~[SchedulerHelper.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
13:42:35 at org.spongepowered.common.service.scheduler.SyncScheduler.getScheduledTasks(SyncScheduler.java:103) ~[SyncScheduler.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
13:42:35 at blue.lapis.pore.impl.scheduler.PoreBukkitScheduler.cancelTasks(PoreBukkitScheduler.java:94) ~[PoreBukkitScheduler.class:1.0.0-SNAPSHOT]
13:42:35 at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.0.0-SNAPSHOT]
13:42:35 at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:416) [SimplePluginManager.class:1.0.0-SNAPSHOT]
13:42:35 at blue.lapis.pore.impl.PoreServer.disablePlugins(PoreServer.java:197) [PoreServer.class:1.0.0-SNAPSHOT]
13:42:35 at blue.lapis.pore.Pore.onShutdown(Pore.java:116) [Pore.class:1.0.0-SNAPSHOT]
13:42:35 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
13:42:35 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at org.spongepowered.mod.plugin.SpongeModPluginContainer.handleModStateEvent(SpongeModPluginContainer.java:126) [SpongeModPluginContainer.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
13:42:35 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
13:42:35 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
13:42:35 at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
13:42:35 at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
13:42:35 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
13:42:35 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
13:42:35 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
13:42:35 at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
13:42:35 at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
13:42:35 at net.minecraftforge.fml.common.Loader.serverStopping(Loader.java:757) [Loader.class:?]
13:42:35 at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:330) [FMLCommonHandler.class:?]
13:42:35 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
13:42:35 at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
13:42:35 [INFO] [pore] Finished disabling Bukkit plugins!
```

**Comment by Minecrell** [comment]
Not a Pore bug actually, although I'll fix this in [SpongeCommon](https://github.com/SpongePowered/SpongeCommon)
