### ISSUE TITLE
Error executing command "/reload"

### ISSUE THREAD

**Issue by sgdc3** [LapisBlue/Pore#15]
```
13:52:40 [INFO] Please note that this command is not supported and may cause issues when using some plugins.
13:52:40 [INFO] If you encounter any issues please use the /stop command to restart your server.
13:52:40 [WARN] [Sponge] A handler raised an error when handling an event
13:52:40 org.bukkit.command.CommandException: Unhandled exception executing 'reload' in org.bukkit.command.defaults.ReloadCommand(reload)
13:52:40 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:1.0.0-SNAPSHOT]
13:52:40 at blue.lapis.pore.impl.PoreServer.dispatchCommand(PoreServer.java:485) ~[PoreServer.class:1.0.0-SNAPSHOT]
13:52:40 at blue.lapis.pore.Pore.onCommand(Pore.java:132) ~[Pore.class:1.0.0-SNAPSHOT]
13:52:40 at org.spongepowered.mod.event.handler.CommandEventHandler_Pore_onCommand3.handle(Unknown Source) ~[?:?]
13:52:40 at org.spongepowered.mod.event.SpongeEventBus.callListener(SpongeEventBus.java:234) [SpongeEventBus.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
13:52:40 at org.spongepowered.mod.event.SpongeEventBus.post(SpongeEventBus.java:280) [SpongeEventBus.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
13:52:40 at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:224) [SimpleCommandService.class:1.8-1371-2.1DEV-433+unknown-b433.git-unknown]
13:52:40 at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:85) [cl.class:?]
13:52:41 at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400) [po.class:?]
13:52:41 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:365) [po.class:?]
13:52:41 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
13:52:41 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
13:52:41 at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
13:52:41 Caused by: java.lang.UnsupportedOperationException
13:52:41 at blue.lapis.pore.impl.PoreServer.reload(PoreServer.java:456) ~[PoreServer.class:1.0.0-SNAPSHOT]
13:52:41 at org.bukkit.Bukkit.reload(Bukkit.java:543) ~[Bukkit.class:1.0.0-SNAPSHOT]
13:52:41 at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) ~[ReloadCommand.class:1.0.0-SNAPSHOT]
13:52:41 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:1.0.0-SNAPSHOT]
13:52:41 ... 12 more
13:52:41 [INFO] Unknown command. Try /help for a list of commands
```

**Comment by Minecrell** [comment]
```
13:52:40 [INFO] Please note that this command is not supported and may cause issues when using some plugins.
13:52:40 [INFO] If you encounter any issues please use the /stop command to restart your server.
```
We may disable the command directly later, but for now it is simply unsupported.
