### ISSUE TITLE
Doesnt seem to work for me for some reason :( 

### ISSUE THREAD

**Issue by LunaticXCrazy** [LapisBlue/Pore#22]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0xffffffffa37a5120, pid=35380, tid=40116
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0xffffffffa37a5120
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x000000000214d800):  JavaThread "main" [_thread_in_Java, id=40116, stack(0x00000000023d0000,0x00000000024d0000)]

siginfo: ExceptionCode=0xc0000005, ExceptionInformation=0x0000000000000008 0xffffffffa37a5120

Registers:
RAX=0x00000000545dfe98, RBX=0x00000000545dfe98, RCX=0x00000000eb2c1d00, RDX=0x00000000eb2c1d00
RSP=0x00000000024ce028, RBP=0x00000000024ce098, RSI=0x00000000eb2c1d88, RDI=0x000000006e39275a
R8 =0x00000000eb14f890, R9 =0x000000000000c240, R10=0x00000000608d2140, R11=0x00000000028f0f40
R12=0x0000000000000000, R13=0x00000000024ce040, R14=0x0000000000000000, R15=0x000000000214d800
RIP=0xffffffffa37a5120, EFLAGS=0x0000000000010206

Top of Stack: (sp=0x00000000024ce028)
0x00000000024ce028:   00000000027a7a01 0000000000000000
0x00000000024ce038:   00000000027a7a01 000000000000c240
0x00000000024ce048:   00000000eb14f890 00000000eb2c1d00
0x00000000024ce058:   00000000024ce058 00000000545e0848
0x00000000024ce068:   00000000024ce0c0 00000000545e0df0
0x00000000024ce078:   0000000000000000 00000000545e0858
0x00000000024ce088:   00000000024ce040 00000000024ce0a8
0x00000000024ce098:   00000000024ce108 00000000027a7450
0x00000000024ce0a8:   000000000001f569 000000000000c240
0x00000000024ce0b8:   00000000eb14f890 00000000eb2c1d00
0x00000000024ce0c8:   00000000024ce0c8 00000000545e0797
0x00000000024ce0d8:   00000000024ce138 00000000545e0df0
0x00000000024ce0e8:   0000000000000000 00000000545e07b8
0x00000000024ce0f8:   00000000024ce0a8 00000000024ce120
0x00000000024ce108:   00000000024ce180 00000000027a7a01
0x00000000024ce118:   000000000001f5a9 000000000001f5a9 

Instructions: (pc=0xffffffffa37a5120)
0xffffffffa37a5100:   
[error occurred during error reporting (printing registers, top of stack, instructions near pc), id 0xc0000005]

Register to memory mapping:

RAX={method} {0x00000000545dfea0} 'implCompress' '([BI)V' in 'sun/security/provider/SHA'
RBX={method} {0x00000000545dfea0} 'implCompress' '([BI)V' in 'sun/security/provider/SHA'
RCX=0x00000000eb2c1d00 is an oop
sun.security.provider.SHA 
 - klass: 'sun/security/provider/SHA'
RDX=0x00000000eb2c1d00 is an oop
sun.security.provider.SHA 
 - klass: 'sun/security/provider/SHA'
RSP=0x00000000024ce028 is pointing into the stack for thread: 0x000000000214d800
RBP=0x00000000024ce098 is pointing into the stack for thread: 0x000000000214d800
RSI=0x00000000eb2c1d88 is an oop
[I 
 - klass: {type array int}
 - length: 5
RDI=0x000000006e39275a is an unknown value
R8 =0x00000000eb14f890 is an oop
[B 
 - klass: {type array byte}
 - length: 128425
R9 =0x000000000000c240 is an unknown value
R10=0x00000000608d2140 is an unknown value
R11=0x00000000028f0f40 is at entry_point+32 in (nmethod*)0x00000000028f0d50
R12=0x0000000000000000 is an unknown value
R13=0x00000000024ce040 is pointing into the stack for thread: 0x000000000214d800
R14=0x0000000000000000 is an unknown value
R15=0x000000000214d800 is a thread


Stack: [0x00000000023d0000,0x00000000024d0000],  sp=0x00000000024ce028,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0xffffffffa37a5120


---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00000000560a8800 JavaThread "Service Thread" daemon [_thread_blocked, id=26420, stack(0x0000000056660000,0x0000000056760000)]
  0x0000000054c57000 JavaThread "C1 CompilerThread1" daemon [_thread_blocked, id=124824, stack(0x0000000055fa0000,0x00000000560a0000)]
  0x0000000054c4d800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=28728, stack(0x0000000055c80000,0x0000000055d80000)]
  0x0000000054c48000 JavaThread "Attach Listener" daemon [_thread_blocked, id=89932, stack(0x0000000055dc0000,0x0000000055ec0000)]
  0x0000000054c46800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=187076, stack(0x0000000055b60000,0x0000000055c60000)]
  0x0000000054beb800 JavaThread "Finalizer" daemon [_thread_blocked, id=34136, stack(0x0000000055a40000,0x0000000055b40000)]
  0x0000000054be4800 JavaThread "Reference Handler" daemon [_thread_blocked, id=124884, stack(0x0000000055880000,0x0000000055980000)]
=>0x000000000214d800 JavaThread "main" [_thread_in_Java, id=40116, stack(0x00000000023d0000,0x00000000024d0000)]

Other Threads:
  0x0000000054bdc800 VMThread [stack: 0x00000000556a0000,0x00000000557a0000] [id=48272]
  0x00000000560b8000 WatcherThread [stack: 0x00000000567d0000,0x00000000568d0000] [id=28264]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 15360K, used 10196K [0x00000000eab00000, 0x00000000ec900000, 0x0000000100000000)
  eden space 13312K, 61% used [0x00000000eab00000,0x00000000eb2f7b30,0x00000000eb800000)
  from space 2048K, 99% used [0x00000000eb800000,0x00000000eb9fd650,0x00000000eba00000)
  to   space 2048K, 0% used [0x00000000ec700000,0x00000000ec700000,0x00000000ec900000)
 ParOldGen       total 35840K, used 2079K [0x00000000c0000000, 0x00000000c2300000, 0x00000000eab00000)
  object space 35840K, 5% used [0x00000000c0000000,0x00000000c0207dd8,0x00000000c2300000)
 Metaspace       used 8352K, capacity 8428K, committed 8576K, reserved 1056768K
  class space    used 1006K, capacity 1042K, committed 1152K, reserved 1048576K

Card table byte_map: [0x0000000011b60000,0x0000000011d70000] byte_map_base: 0x0000000011560000

Marking Bits: (ParMarkBitMap*) 0x00000000608ea5b0
 Begin Bits: [0x00000000120b0000, 0x00000000130b0000)
 End Bits:   [0x00000000130b0000, 0x00000000140b0000)

Polling page: 0x0000000000440000

CodeCache: size=245760Kb used=2765Kb max_used=2779Kb free=242994Kb
 bounds [0x00000000027a0000, 0x0000000002a60000, 0x00000000117a0000]
 total_blobs=1020 nmethods=689 adapters=246
 compilation: enabled

Compilation events (10 events):
Event: 1.551 Thread 0x0000000054c57000  685       3       java.util.jar.Attributes::clone (9 bytes)
Event: 1.552 Thread 0x0000000054c57000 nmethod 685 0x0000000002a46f50 code [0x0000000002a470e0, 0x0000000002a475a8]
Event: 1.552 Thread 0x0000000054c57000  686       3       java.util.jar.Attributes::<init> (17 bytes)
Event: 1.552 Thread 0x0000000054c57000 nmethod 686 0x0000000002a47810 code [0x0000000002a479a0, 0x0000000002a47dc8]
Event: 1.573 Thread 0x0000000054c57000  688       3       java.io.ByteArrayInputStream::mark (9 bytes)
Event: 1.573 Thread 0x0000000054c57000 nmethod 688 0x0000000002a47f90 code [0x0000000002a480e0, 0x0000000002a48230]
Event: 1.579 Thread 0x0000000054c57000  689       3       sun.security.util.DerValue::isPrintableStringChar (184 bytes)
Event: 1.580 Thread 0x0000000054c57000 nmethod 689 0x0000000002a48290 code [0x0000000002a48400, 0x0000000002a486f0]
Event: 1.580 Thread 0x0000000054c57000  690       3       sun.security.provider.SHA::implCompress (491 bytes)
Event: 1.580 Thread 0x0000000054c57000 nmethod 690 0x0000000002a48750 code [0x0000000002a48940, 0x0000000002a49228]

GC Heap History (2 events):
Event: 1.184 GC heap before
{Heap before GC invocations=1 (full 0):
 PSYoungGen      total 15360K, used 13312K [0x00000000eab00000, 0x00000000ebc00000, 0x0000000100000000)
  eden space 13312K, 100% used [0x00000000eab00000,0x00000000eb800000,0x00000000eb800000)
  from space 2048K, 0% used [0x00000000eba00000,0x00000000eba00000,0x00000000ebc00000)
  to   space 2048K, 0% used [0x00000000eb800000,0x00000000eb800000,0x00000000eba00000)
 ParOldGen       total 35840K, used 0K [0x00000000c0000000, 0x00000000c2300000, 0x00000000eab00000)
  object space 35840K, 0% used [0x00000000c0000000,0x00000000c0000000,0x00000000c2300000)
 Metaspace       used 7536K, capacity 7648K, committed 7936K, reserved 1056768K
  class space    used 893K, capacity 912K, committed 1024K, reserved 1048576K
Event: 1.197 GC heap after
Heap after GC invocations=1 (full 0):
 PSYoungGen      total 15360K, used 2037K [0x00000000eab00000, 0x00000000ec900000, 0x0000000100000000)
  eden space 13312K, 0% used [0x00000000eab00000,0x00000000eab00000,0x00000000eb800000)
  from space 2048K, 99% used [0x00000000eb800000,0x00000000eb9fd650,0x00000000eba00000)
  to   space 2048K, 0% used [0x00000000ec700000,0x00000000ec700000,0x00000000ec900000)
 ParOldGen       total 35840K, used 2079K [0x00000000c0000000, 0x00000000c2300000, 0x00000000eab00000)
  object space 35840K, 5% used [0x00000000c0000000,0x00000000c0207dd8,0x00000000c2300000)
 Metaspace       used 7536K, capacity 7648K, committed 7936K, reserved 1056768K
  class space    used 893K, capacity 912K, committed 1024K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 0.684 Thread 0x000000000214d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000294f4e8 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 0.684 Thread 0x000000000214d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000294f4e8 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 0.825 Thread 0x000000000214d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000002957f58 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 253
Event: 0.850 Thread 0x000000000214d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000002957f58 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 253
Event: 0.866 Thread 0x000000000214d800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x0000000002988174 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 0.867 Thread 0x000000000214d800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x0000000002988174 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 0.872 Thread 0x000000000214d800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x0000000002988174 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 0.898 Thread 0x000000000214d800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000002990410 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 181
Event: 1.199 Thread 0x000000000214d800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000002924c48 method=java.lang.ref.SoftReference.get()Ljava/lang/Object; @ 17
Event: 1.298 Thread 0x000000000214d800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000002918024 method=java.lang.ref.SoftReference.get()Ljava/lang/Object; @ 17

Internal exceptions (10 events):
Event: 0.690 Thread 0x000000000214d800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000eb27c750) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.881 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4b43a8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.882 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4b5120) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.882 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4b60d8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.884 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4b7998) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.920 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4ddc90) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.921 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4deef8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.922 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb4e0e28) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.964 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb506c30) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]
Event: 0.974 Thread 0x000000000214d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000000eb5161e0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u60\4407\hotspot\src\share\vm\runtime\sharedRuntime.cpp, line 605]

Events (10 events):
Event: 1.580 Thread 0x000000000214d800 DEOPT PACKING pc=0x00000000028f1529 sp=0x00000000024cdfd0
Event: 1.580 Thread 0x000000000214d800 DEOPT UNPACKING pc=0x00000000027e71bf sp=0x00000000024cdce8 mode 0
Event: 1.580 Thread 0x000000000214d800 DEOPT PACKING pc=0x00000000028f1529 sp=0x00000000024cdfd0
Event: 1.580 Thread 0x000000000214d800 DEOPT UNPACKING pc=0x00000000027e71bf sp=0x00000000024cdce8 mode 0
Event: 1.580 Thread 0x000000000214d800 DEOPT PACKING pc=0x00000000028f1529 sp=0x00000000024cdfd0
Event: 1.580 Thread 0x000000000214d800 DEOPT UNPACKING pc=0x00000000027e71bf sp=0x00000000024cdce8 mode 0
Event: 1.580 Thread 0x000000000214d800 DEOPT PACKING pc=0x00000000028f1529 sp=0x00000000024cdfd0
Event: 1.580 Thread 0x000000000214d800 DEOPT UNPACKING pc=0x00000000027e71bf sp=0x00000000024cdce8 mode 0
Event: 1.580 Thread 0x000000000214d800 DEOPT PACKING pc=0x00000000028f1529 sp=0x00000000024cdfd0
Event: 1.580 Thread 0x000000000214d800 DEOPT UNPACKING pc=0x00000000027e71bf sp=0x00000000024cdce8 mode 0


Dynamic libraries:
0x000000013fe60000 - 0x000000013fe97000 	C:\ProgramData\Oracle\Java\javapath\java.exe
0x0000000077bc0000 - 0x0000000077d69000 	C:\Windows\SYSTEM32\ntdll.dll
0x00000000779a0000 - 0x0000000077abf000 	C:\Windows\system32\kernel32.dll
0x000007fefdc70000 - 0x000007fefdcdc000 	C:\Windows\system32\KERNELBASE.dll
0x000007feff650000 - 0x000007feff72b000 	C:\Windows\system32\ADVAPI32.dll
0x000007fefe820000 - 0x000007fefe8bf000 	C:\Windows\system32\msvcrt.dll
0x000007fefe600000 - 0x000007fefe61f000 	C:\Windows\SYSTEM32\sechost.dll
0x000007feffda0000 - 0x000007feffecd000 	C:\Windows\system32\RPCRT4.dll
0x0000000077ac0000 - 0x0000000077bba000 	C:\Windows\system32\USER32.dll
0x000007fefe620000 - 0x000007fefe687000 	C:\Windows\system32\GDI32.dll
0x000007fefded0000 - 0x000007fefdede000 	C:\Windows\system32\LPK.dll
0x000007fefe240000 - 0x000007fefe309000 	C:\Windows\system32\USP10.dll
0x000007fefc710000 - 0x000007fefc904000 	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_fa3b1e3d17594757\COMCTL32.dll
0x000007fefe0b0000 - 0x000007fefe121000 	C:\Windows\system32\SHLWAPI.dll
0x000007fefe5d0000 - 0x000007fefe5fe000 	C:\Windows\system32\IMM32.DLL
0x000007fefe130000 - 0x000007fefe239000 	C:\Windows\system32\MSCTF.dll
0x000000006dff0000 - 0x000000006e0c2000 	C:\Program Files\Java\jre1.8.0_60\bin\msvcr100.dll
0x00000000600e0000 - 0x0000000060969000 	C:\Program Files\Java\jre1.8.0_60\bin\server\jvm.dll
0x000007fef4e20000 - 0x000007fef4e29000 	C:\Windows\system32\WSOCK32.dll
0x000007fefe310000 - 0x000007fefe35d000 	C:\Windows\system32\WS2_32.dll
0x000007feff910000 - 0x000007feff918000 	C:\Windows\system32\NSI.dll
0x000007fefac40000 - 0x000007fefac7b000 	C:\Windows\system32\WINMM.dll
0x000007fefcc00000 - 0x000007fefcc0c000 	C:\Windows\system32\VERSION.dll
0x0000000077d90000 - 0x0000000077d97000 	C:\Windows\system32\PSAPI.DLL
0x0000000072680000 - 0x000000007268f000 	C:\Program Files\Java\jre1.8.0_60\bin\verify.dll
0x000000006f120000 - 0x000000006f149000 	C:\Program Files\Java\jre1.8.0_60\bin\java.dll
0x0000000070350000 - 0x0000000070366000 	C:\Program Files\Java\jre1.8.0_60\bin\zip.dll
0x000007fefe8c0000 - 0x000007feff649000 	C:\Windows\system32\SHELL32.dll
0x000007fefe3c0000 - 0x000007fefe5c3000 	C:\Windows\system32\ole32.dll
0x000007fefdac0000 - 0x000007fefdacf000 	C:\Windows\system32\profapi.dll
0x0000000072690000 - 0x000000007269d000 	C:\Program Files\Java\jre1.8.0_60\bin\management.dll
0x000000006faa0000 - 0x000000006faba000 	C:\Program Files\Java\jre1.8.0_60\bin\net.dll
0x000007fefd2f0000 - 0x000007fefd345000 	C:\Windows\system32\mswsock.dll
0x000007fefd2e0000 - 0x000007fefd2e7000 	C:\Windows\System32\wship6.dll
0x000000006fa80000 - 0x000000006fa91000 	C:\Program Files\Java\jre1.8.0_60\bin\nio.dll
0x000007feee7c0000 - 0x000007feee8e5000 	C:\Windows\system32\dbghelp.dll

VM Arguments:
jvm_args: -Xmx1024M 
java_command: minecraft_server.jar -o true
java_class_path (initial): minecraft_server.jar
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\SlickEdit Pro 19.0.2\win\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\010 Editor;
USERNAME=Todor
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 15 Stepping 13, GenuineIntel



---------------  S Y S T E M  ---------------

OS: Windows 7 , 64 bit Build 7601 (6.1.7601.18939)

CPU:total 2 (2 cores per cpu, 1 threads per core) family 6 model 15 stepping 13, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, tsc

Memory: 4k page, physical 3406388k(461868k free), swap 6896524k(2126200k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.60-b23) for windows-amd64 JRE (1.8.0_60-b27), built on Aug  4 2015 11:06:27 by "java_re" with MS VC++ 10.0 (VS2010)

time: Wed Sep 23 21:23:00 2015
elapsed time: 1 seconds (0d 0h 0m 1s)

```

**Comment by caseif** [comment]
Does this occur when the server is loaded without Pore?

**Comment by LunaticXCrazy** [comment]
Yes

**Comment by caseif** [comment]
What build of Sponge are you using? Also, are you using SpongeForge or SpongeVanilla?

**Comment by LunaticXCrazy** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge-1.8-1499-2.1DEV-650.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/23/15 10:08 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/spongepowered/api/event/state/ServerStoppingEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethods(Unknown Source)
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.findStateEventHandlers(SpongeModPluginContainer.java:136)
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.state.ServerStoppingEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 32 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 34 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161188984 bytes (153 MB) / 455606272 bytes (434 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	UC	Forge{11.14.3.1450} [Minecraft Forge] (minecraft_server.jar) 
	UC	Sponge{1.8-1499-2.1DEV-650} [SpongeForge] (minecraft.jar) 
	UC	customnpcs{1.8.0_beta} [CustomNPCs] (CustomNPCs_1.8.0_beta.jar) 
	UC	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	U	pore{unknown} [Pore] (Pore-1.0.0-SNAPSHOT.jar) 
	U	SpongeEssentialCmds{2.8} [SpongeEssentialCmds] (SpongeEssentialCmds-2.8e.jar) 
	U	supersentai{1.0.0} [SuperSentai] (SuperSentaiMod-v.1.0.0-forge-1.8-11.14.1.1341.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (sponge-1.8-1499-2.1DEV-650.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by jamierocks** [comment]
Your using too a recent version of Sponge :)

Pore has yet to catch up :P

**Comment by LunaticXCrazy** [comment]
Okay what version do i use for Pore? Your plugin/mod is amazing and i realy need bukkit plugins in my 1.8 moddes server xS

**Comment by caseif** [comment]
Build #592 is the last build that we can guarantee Pore won't completely explode with. There were some major changes made in the next available build (#602) that we haven't updated Pore for yet.

Also, keep in mind that Pore is still in a very early stage, and around half of the Bukkit API still isn't implemented, so most plugins will not function 100% properly.

**Comment by LunaticXCrazy** [comment]
Okay ofc i understand its still being made but i will try it anyway i got nothing to lose realy ^^ 
Keep up the good work and you can close this issue :3 :+1:

**Comment by LunaticXCrazy** [comment]
Here is some things i found not working but everything else works when i use Essentiels ^^ so i mean like i never imagined my self having bukkit plugins so yeah i am happy even thos some things dont work i have way more freedom than i had with sponge plugins :+1: :smile: And i was wondering why do you not work on world edit? For me i think you should it will take i think a lot of time for it to show up on sponge and your plugin/mod Pore is awesome(sory for reapiting but it is) :3
![1](https://cloud.githubusercontent.com/assets/11874010/10080088/f40172d8-62ed-11e5-8ec8-216d256a8561.png)
![2](https://cloud.githubusercontent.com/assets/11874010/10080087/f3fe09b8-62ed-11e5-8f49-b80ddda5d131.png)
![3](https://cloud.githubusercontent.com/assets/11874010/10080091/f405002e-62ed-11e5-9186-5656d97da11e.png)
![4](https://cloud.githubusercontent.com/assets/11874010/10080089/f401bc5c-62ed-11e5-8fba-e2935cd01b0e.png)
![5](https://cloud.githubusercontent.com/assets/11874010/10080090/f40494e0-62ed-11e5-9248-fb952cc761db.png)
If this could be fixed i think this will be revolutionery xS and i know Pore is not stable or the best stable version so far but hey Good Luck on fixing this if you fix it pls post it here or message me if you can do that on gith i am new anyways :P

**Comment by caseif** [comment]
Again, Pore is still in an early stage and will contain many bugs and unsupported features. You'll have to bear with us as we progress in its development. WorldEdit will not be supported because it uses NMS, which Pore cannot reliably bridge. In any case, its author is currently developing a native Sponge version.

**Comment by LunaticXCrazy** [comment]
And again i say i know :D Well hope you make Pore work for latest version or versions ^^ and good luck thats all from me :D :+1:
