### ISSUE TITLE
World edit and relatded

### ISSUE THREAD

**Issue by Hansoeaung** [LapisBlue/Pore#27]
Hi I tried your recomplied pore and tried to run a survival plugins that uses world edit or plugins relatded to world edit but only survival games plugins work. I tried all kinds of versions and plugins but nothing worked. Here is the error code for world edite: [18:07:06 ERROR] [pore]: Error occurred while enabling WorldEdit v6.1;no_git_id (Is it up to date?)
java.lang.ExceptionInInitializerError
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.<init>(BukkitServerInterface.java:59) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:104) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Pore-1.0.0-SNAPSHOT.jar!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Pore-1.0.0-SNAPSHOT.jar!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Pore-1.0.0-SNAPSHOT.jar!/:?]
        at blue.lapis.pore.impl.PoreServer.loadPlugin(PoreServer.java:169) [Pore-1.0.0-SNAPSHOT.jar!/:?]
        at blue.lapis.pore.impl.PoreServer.enablePlugins(PoreServer.java:186) [Pore-1.0.0-SNAPSHOT.jar!/:?]
        at blue.lapis.pore.Pore.onStarting(Pore.java:119) [Pore-1.0.0-SNAPSHOT.jar!/:?]
        at blue.lapis.pore.launch.PoreBootstrap.onStarting(PoreBootstrap.java:87) [PoreBootstrap.class:1.0.0-SNAPSHOT-git(master-51b5f94)-jnks280]
        at org.spongepowered.common.event.listener.GameStartingServerEventListener_PoreBootstrap_onStarting5.handle(Unknown Source) [?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) [RegisteredListener.class:1.8.9-3.1.0-BETA-224]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:258) [SpongeEventManager.class:1.8.9-3.1.0-BETA-224]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:269) [SpongeEventManager.class:1.8.9-3.1.0-BETA-224]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:273) [SpongeEventManager.class:1.8.9-3.1.0-BETA-224]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:183) [SpongeImpl.class:1.8.9-3.1.0-BETA-224]
        at org.spongepowered.server.SpongeVanilla.onServerStarting(SpongeVanilla.java:180) [SpongeVanilla.class:1.8.9-3.1.0-BETA-224]
        at net.minecraft.server.dedicated.DedicatedServer.callServerStarting(SourceFile:80) [ko.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:211) [ko.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:421) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: org.apache.commons.lang3.NotImplementedException: TODO
        at blue.lapis.pore.impl.help.PoreHelpMap.registerHelpTopicFactory(PoreHelpMap.java:59) ~[PoreHelpMap.class:1.0.0-SNAPSHOT-git(master-51b5f94)-jnks280]
        at com.sk89q.bukkit.util.CommandRegistration.<clinit>(CommandRegistration.java:38) ~[?:?]
        ... 20 more

**Comment by Minecrell** [comment]
Pore isn't finished, and cannot run all plugins currently. However, WorldEdit for Bukkit will **never** be supported on Pore anyway, because there is a version available for SpongeForge and SpongeVanilla: https://forums.spongepowered.org/t/worldedit-for-spongeforge-and-spongevanilla/10649?u=minecrell

**Comment by Hansoeaung** [comment]
No it must be supported by pore. Why? plugins in bukkit use's a bukkit world edite and can't use the sponge version of it I tried it.

**Comment by Minecrell** [comment]
Well I kind of fixed it for now, you can try if the latest Pore fixes your issue.
