### ISSUE TITLE
Please fix crash on AAC

### ISSUE THREAD

**Issue by DarkWav** [LapisBlue/Pore#28]
Crash:
[07:46:46] [Server thread/INFO] [pore.AAC]: Enabling AAC v1.9.7
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      at me.konsolas.aac.i.b.B.run(Unknown Source)
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      at java.net.URLClassLoader.findClass(Unknown Source)
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      at java.lang.ClassLoader.loadClass(Unknown Source)
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      at java.lang.ClassLoader.loadClass(Unknown Source)
[07:46:46] [Thread-9/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:      ... 1 more

**Comment by Minecrell** [comment]
Pore doesn't support ProtocolLib currently because it depends on internal NMS code that bypasses the BukkitAPI
